module.exports = {
  User: require('./User'),
  Rider: require('./Rider'),
  Admin: require('./Admin'),
  Otp: require('./Otp'),
  Booking: require('./Booking'),
  FareConfig: require('./FareConfig'),
  RiderLocationPing: require('./RiderLocationPing'),
  MatchRequest: require('./MatchRequest'),
  Wallet: require('./Wallet'),
  Transaction: require('./Transaction'),
  Payment: require('./Payment'),
  Rating: require('./Rating'),
  Notification: require('./Notification'),
  SupportTicket: require('./SupportTicket'),
  BookingMessage: require('./BookingMessage'),
  CallLog: require('./CallLog'),
  FraudFlag: require('./FraudFlag'),
  BusinessAccount: require('./BusinessAccount'),
  WaitlistSignup: require('./WaitlistSignup'),
};
